export const stepFieldMap: Record<number, string[]> = {
  1: ["consent.authorized", "consent.privacyAccepted"],
  2: [
    "schoolContact.schoolName",
    "schoolContact.schoolDistrict",
    "schoolContact.city",
    "schoolContact.state",
    "schoolContact.zipCode",
    "schoolContact.schoolType",
    "schoolContact.schoolTypeOther",
    "schoolContact.schoolSetting",
    "schoolContact.enrollment",
    "schoolContact.contactName",
    "schoolContact.contactRole",
    "schoolContact.email",
    "schoolContact.phone",
  ],
  3: [
    "safetyStatus.campusSafety",
    "safetyStatus.emergencyConfidence",
    "safetyStatus.policyConsistency",
    "safetyStatus.emergencyPlanning",
    "safetyStatus.accessControl",
    "safetyStatus.threatAssessmentProtocols",
  ],
  4: [
    "incidents.incidentTypes",
    "incidents.incidentOther",
    "incidents.incidentFrequency",
    "incidents.topConcerns",
  ],
  5: [
    "systemsResources.emergencyPlanStatus",
    "systemsResources.threatAssessmentTeam",
    "systemsResources.drillFrequency",
    "systemsResources.mentalHealthSupport",
    "systemsResources.firstResponderRelationship",
    "systemsResources.staffTrainingLevel",
  ],
  6: [
    "physicalSecurity.entryProcedure",
    "physicalSecurity.securityFeatures",
    "physicalSecurity.hasVulnerabilities",
    "physicalSecurity.vulnerabilitiesDescription",
  ],
  7: [
    "capacityBarriers.implementationCapacity",
    "capacityBarriers.barriers",
    "capacityBarriers.barriersOther",
    "capacityBarriers.urgency",
  ],
  8: [
    "services.supportTypes",
    "services.supportTypesOther",
    "services.preferredTimeframe",
    "services.additionalInformation",
  ],
  9: ["finalConfirmation.agreeToSubmit"],
} as const;
